export const DESIGN_PALETTE_NAME = "Luminous Minimalist";

export const designColors = {
  surface: "#0b1326",
  "surface-dim": "#0b1326",
  "surface-bright": "#31394d",
  "surface-container-lowest": "#060e20",
  "surface-container-low": "#131b2e",
  "surface-container": "#171f33",
  "surface-container-high": "#222a3d",
  "surface-container-highest": "#2d3449",
  "on-surface": "#dae2fd",
  "on-surface-variant": "#c2c6d6",
  "inverse-surface": "#dae2fd",
  "inverse-on-surface": "#283044",
  outline: "#8c909f",
  "outline-variant": "#424754",
  "surface-tint": "#adc6ff",
  primary: "#adc6ff",
  "on-primary": "#002e6a",
  "primary-container": "#4d8eff",
  "on-primary-container": "#00285d",
  "inverse-primary": "#005ac2",
  secondary: "#c0c1ff",
  "on-secondary": "#1000a9",
  "secondary-container": "#3131c0",
  "on-secondary-container": "#b0b2ff",
  tertiary: "#89ceff",
  "on-tertiary": "#00344d",
  "tertiary-container": "#009ada",
  "on-tertiary-container": "#002d43",
  error: "#ffb4ab",
  "on-error": "#690005",
  "error-container": "#93000a",
  "on-error-container": "#ffdad6",
  "primary-fixed": "#d8e2ff",
  "primary-fixed-dim": "#adc6ff",
  "on-primary-fixed": "#001a42",
  "on-primary-fixed-variant": "#004395",
  "secondary-fixed": "#e1e0ff",
  "secondary-fixed-dim": "#c0c1ff",
  "on-secondary-fixed": "#07006c",
  "on-secondary-fixed-variant": "#2f2ebe",
  "tertiary-fixed": "#c9e6ff",
  "tertiary-fixed-dim": "#89ceff",
  "on-tertiary-fixed": "#001e2f",
  "on-tertiary-fixed-variant": "#004c6e",
  background: "#0b1326",
  "on-background": "#dae2fd",
  "surface-variant": "#2d3449",
} as const;

export type DesignColorName = keyof typeof designColors;

export const getDesignColorCssVariable = (colorName: DesignColorName) =>
  `var(--revisor-color-${colorName})`;
